# Working directory
root = "."
tmp_dir = "tmp"

[build]
  # Command to build your app
  cmd = "go build -o ./tmp/main ."

  # Binary file location
  bin = "tmp/main"

  # Files to watch
  include_ext = ["go", "tpl", "tmpl", "html"]

  # Ignore these folders
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]

  # Ignore test files
  exclude_regex = ["_test.go"]

  # Delay after change (ms)
  delay = 1000

  # Stop running binary before rebuild
  stop_on_error = true

  # Log file
  log = "air_errors.log"

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[misc]
  clean_on_exit = true